CREATE TABLE crud (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    password TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TRIGGER update_crud_updated_at
AFTER UPDATE ON crud
FOR EACH ROW
BEGIN
    UPDATE crud SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
